import 'package:riverpod_annotation/riverpod_annotation.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

// This file will be generated by Riverpod
part 'auth_provider.g.dart';

final supabase = Supabase.instance.client;

// 1. Stream: Listens to Login/Logout events instantly
@riverpod
Stream<AuthState> authState(AuthStateRef ref) {
  return supabase.auth.onAuthStateChange;
}

// 2. Future: Fetches the User's Role from the profiles table
@riverpod
Future<String?> userRole(UserRoleRef ref) async {
  final user = supabase.auth.currentUser;

  if (user == null) return null;

  try {
    final response = await supabase
        .from('profiles')
        .select('role')
        .eq('id', user.id)
        .single();

    return response['role'] as String?;
  } catch (e) {
    // If they have no profile yet, default to client
    return 'client';
  }
}
